on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-22.04
          - windows-2022
        # We want to ensure the repo works across OS's, but it's not worth blocking PRs on
        # all the builds, especially slow ones like Windows. We will fix-forward if an issue
        # comes up on main push. Also, use workaround from
        # https://github.com/orgs/community/discussions/26253#discussioncomment-3250989
        run-all:
          - ${{ github.event_name != 'pull_request' && !startsWith(github.ref_name, 'release/') }}
        exclude:
          - os: macos-14
            run-all: false
          - os: windows-2022
            run-all: false

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: package.json

      - run: bun install

      - name: run lints
        # We don't have OS-specific code so would be completely repetitive to run
        # lint on all of them.
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: bun run lint
